### ISSUE TITLE
verify elf file integrity and termination of sequences

### ISSUE THREAD

**Issue by ChristianBeer** [MersenneForum/MersenneForumAliquot#16]
Because sequences in FDB can be broken and show as terminated when they are not, it is important to check the FDB generated ELF file when a termination is detected. Originally I wanted to use the aliqueit tool to do this but it seems easier to migrate the [parse_elf() function](https://github.com/ChristianBeer/aliqueit/blob/master/src/aliqueit/aliqueit.cc#L712) from C++ to python and integrate this with the current scripts.

First thoughts:
- Have a separate script run once a day that tests all sequences in `allseq.terms.txt`
- The script downloads the ELF from FDB and verifies it
- If the sequence terminates, it will be added to `allseq.drops.txt`, if not an email is send and it will be added to `allseq.broken.txt`
- We don't necessarily need a standalone script but downloading the ELF takes some time so I want to do it outside of the normal update cycle

**Comment by dubslow** [comment]
I was just gonna use aliqueit. See https://github.com/MersenneForum/MersenneForumAliquot/commits/verify_terms

**Comment by ChristianBeer** [comment]
The problem with `aliqueit -t` is that it also exits 0 if the sequence does not terminate but the file is valid. I was about to add a more thorough test when I realized it would be easier to just adapt the verification function to python. The benefit would be that I don't need to compile aliqueit on the RKN server (it has an older glibc which is incompatible with mine).

**Comment by dubslow** [comment]
Hmm. I noticed that too, but I figured that relying on the lower merged sequences to also terminate isn't much of a burden.

Compiling shouldn't be too hard, and even tweaking aliqueit -t should also be easier than doing it in Python. Having made those arguments though, if you would still prefer to do it in Python, I'll defer.

**Comment by ChristianBeer** [comment]
I still would like to do this in python. Less moving parts that need to be taken care of in the future.

**Comment by dubslow** [comment]
Er, actually the merge detector can be disabled by using a one line configuration file. I've already tested the whole thing in the branch mentioned in the commit above. It all works right now, using aliqueit, to test the *entire* elf file.

**Comment by ChristianBeer** [comment]
Yes, but the aliqueit verification does not test if the sequence really terminates (as in: is the last index a prime). I would need to add this to aliqueit with a new config option and then setup the C++ build system and all (aliqueit also requires libgmp which we don't need for this at all and I don't know if it is available on this old system).

**Comment by dubslow** [comment]
> Yes, but the aliqueit verification does not test if the sequence really terminates (as in: is the last index a prime).

I'm certain that this is not true.  For instance, just now testing with 1268784:

```
./verify_terminations.sh 
--2018-02-14 14:47:02--  http://factordb.com/elf.php?seq=1268784&type=1
Resolving factordb.com (factordb.com)... 138.201.37.196
Connecting to factordb.com (factordb.com)|138.201.37.196|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘alq_1268784.elf’

alq_1268784.elf                                          [             <=>                                                                                                      ] 238.05K  6.81KB/s    in 35s     

2018-02-14 14:47:53 (6.81 KB/s) - ‘alq_1268784.elf’ saved [243768]

Reading config file...
detect_merge = false
Verifying elf 1268784
Verifying index 1815... Elf 1268784 verified OK!
```

Meanwhile the last line reads like this: `1815 .   41 = 41`, and you see it says `Verifying index 1815...`, which means that, according to [this line](https://github.com/ChristianBeer/aliqueit/blob/master/src/aliqueit/aliqueit.cc#L778) and [this line](https://github.com/ChristianBeer/aliqueit/blob/master/src/aliqueit/aliqueit.cc#L689), it has verified that 41 is indeed (probably) prime (with definitive primeness for small numbers according to GMP docs).

As for installing GMP, surely you can do that via your package manager? And isn't compiling aliqueit just done with `make`, no build system?

**Comment by ChristianBeer** [comment]
Delete the last few lines of the file and try again. You'll have the same result but the sequence doesn't terminate. Don't we usually have very low primes that can be easily tested using brute-force?

**Comment by dubslow** [comment]
Actually, we *don't* need to modify anything, because the sequence can only be marked as terminated by `allseq.py` if it ends in a prime or a cycle. aliqueit already does cycle detection, and otherwise we can be sure that the elf file it's checking is indeed a completed sequence -- only the integrity of prior-to-last lines is in doubt. We already know the last line in fact terminates the sequence. So we don't need to worry about that.

**Comment by ChristianBeer** [comment]
The fact that 72708 has a broken index before the current index makes me think it would be better to fully check the ELF generated. We can't exclude the case that although the sequence ended the generated ELF doesn't and we have a broken sequence in FDB. I didn't think about the sequence ending in a cycle which the python implementation would also need to do. I don't see the primality verification of the last index as a problem in python as we are usually dealing with low enough primes. We could always do a manual verification for primes that are too large to do with python. I can't remember a large prime as last index for the sequences terminated since I host the list on RKN.

This is not urgent so let me prepare a python implementation of this within the next weeks and run some tests with it.

**Comment by dubslow** [comment]
I don't see the problem with broken indices. The script as in the pull request correctly detects that 72708 is a false merger, and the error printed by aliqueit indeed points at index 255 as the problem. The entire elf file is completely checked for authenticity.

The problem with primality that I mean is that aliqueit checks that *every factor in the entire elf is (probably) prime*. Meaning that, in order to duplicate what aliqueit can do, we need a way to test n-hundred digit numbers for primality in Python -- decidedly non-trivial, requiring some external dependency (which would most likely depend on gmp anyways, in all probability).

**Comment by dubslow** [comment]
Basically, we're like so:

1a) the aliqueit scripts, as presented in my pull request, currently/already implement everything you've requested. It performs entire-elf verification of every sequence that the FDB purports to be terminated, and records errors in the log for manual investigation (which probably means adding the erroring sequence to the list of brokens, like 72708).

1b) the only drawback is compiling aliqueit on the production server.

2a) the alternative to 1) is to reimplement the aliqueit logic in python. The logic itself is not hard to do, but what is hard to do is probable-primality of hundred-digit-plus numbers, as aliqueit does. Solving this problem will, probably, introduce similar dependencies as compiling aliqueit, if not in fact even worse dependencies.

2b) the drawback, aside from the primality testing thing, is that we'd have to actual write this up, while 1) is already written and ready to go (short of compiling aliqueit, which I genuinely believe to be easier/less effort than finding some full fledged primality testing implementation in python).

**Comment by ChristianBeer** [comment]
After fiddling around with gmpy2 a bit and looking at the aliqueit code again I concede to your arguments and added some additional checks to verify terminations (https://github.com/ChristianBeer/aliqueit/commit/9838af080b273b8c7c64995669f80ea2079447f3) in aliqueit. I'm now going to compile the modified aliqueit on the RKN server and test your scripts.

**Comment by dubslow** [comment]
How difficult was it to compile aliqueit on the server?

**Comment by ChristianBeer** [comment]
As it turns out it was easy as EPEL provided a gmp-devel package and aliqueit uses a simple Makefile. I must have mistaken it with yafu which has more dependencies and on first try I always end up with a yafu binary that just segfaults.

**Comment by dubslow** [comment]
Great to hear. Always fun to kill manual maintenance work :)
