### ISSUE TITLE
Verifying merged sequences too

### ISSUE THREAD

**Issue by dubslow** [MersenneForum/MersenneForumAliquot#18]
It occurs to me that terminations are checked for FDB errors -- shouldn't mergers also be so checked? Is there any reason we aren't doing this as well?

**Comment by ChristianBeer** [comment]
Yes, I also thought about this. I didn't come up with a possible solution at the time because of the different merge types.

Type 1 where the index drops below the starter is easily detected and verifiable by aliqueit on it's own.

Type 2 where two sequences merge with a common index is a bit trickier as you need to verify both sequences individually and then find the common index.

**Comment by ChristianBeer** [comment]
A quick way to find the common index is this:
```
$ cut -d . -f 2 alq_1632.elf > seq1.txt
$ cut -d . -f 2 alq_1255380.elf > seq2.txt
$ grep -F -f seq1.txt seq2.txt | head -n1
   2904 = 2^3 * 3 * 11^2
$ grep -F "2904 = 2^3 * 3 * 11^2" *.elf
alq_1255380.elf:4972 .   2904 = 2^3 * 3 * 11^2
alq_1632.elf:1 .   2904 = 2^3 * 3 * 11^2
```

**Comment by dubslow** [comment]
I'm doubtful that Type 2 actually represents a problem. When a merge is detected, just download the ELF of both of the sequences in question and verify them. Sure there will be duplicated work between the two verifications but it's very easy to code and not a burden by any means.

**Comment by ChristianBeer** [comment]
I also don't see a burden. Only that `aliqueit.ini` needs to be different when testing terminations and when testing mergers right now. Would it make things easier if I removed the `verify_terminations` config option and add a separate commandlineoption? So the same configfile can be used by `verify_terminations.sh` and `verify_merges.sh`.

**Comment by dubslow** [comment]
It can be done either way of course, but the cmdline option is probably the simpler one, at least architecturally

**Comment by ChristianBeer** [comment]
I wrote some code that can read a file that has merge information in it. The line needs to be like this:
```
1632_1255380_999999_...
```
Currently it can only handle a 1 into 1 merge not an N into 1 merge. I'm working on that. It would be nice if you could add some python code that creates this `allseq.merges.txt` whenever a merge is found and calls `verify_merges.sh` at the end. We don't need to use `_` as the separator but it can not be a blank or `#` or `%`.

The scripts finds the common index of the sequences and mails the summary information.
