### ISSUE TITLE
new update action for forum spider

### ISSUE THREAD

**Issue by ChristianBeer** [MersenneForum/MersenneForumAliquot#9]
It should be possible to force an update via the reservation thread on MF. Using the keyword `update` the sequence should be updated as in the complete last index is to be retrieved. No lookup of the stored ID as this seems not to work. Recent examples: `159402 558270` they should both show a C114 as cofactor. Even reserving and unreserving does not trigger a full update. Only running them manually on the commandline seems to do that.

**Comment by ChristianBeer** [comment]
In Slack an idea came up to solve this problem without human intervention. In case of a high priority the sequence is updated less often but when it is updated it should update all factors of the current index not simply check if the current index was fully factored.

While writing this I realize that this idea is already possible since we already look at the factorization of the current index in either case and just need to add a check if it differs from what we currently have stored (instead of looking for `FF` only) this does not need another FDB query and would still be cheap.

The original idea of extending the spider with a new command is still valid as there is a use case where someone does ECM on unreserved sequences without reserving them. We should put in a limit of X maximum updates per request.

**Comment by dubslow** [comment]
I believe we discussed the underlying problem via PM, and I'm still open to improving it.

Note that the code doesn't currently parse the factors of the current ID, it only parses the status -- but you are correct that the HTTP query does indeed retrieve that information, and the code can certainly be improved to parse those factors and compare them. A non-trivial enhancement, but perfectly doable.

**Comment by ChristianBeer** [comment]
From time to time I'd like to dabble in code again so I tried to find an easy way to parse and compare the factors. Use with caution as I only tested this with a [stripped down testscript](https://gist.github.com/ChristianBeer/b48efc3d80c1e7068a95b3b3107c9cfa).
